### ISSUE TITLE
Script for textarea

### ISSUE THREAD

**Issue by harunaltunhr** [harunaltunhr/Mouse-Move-Shadow#3]
- [x] The new repo branch `textarea` generate
- [x]  Create scripts tags for `textarea`
- [x] Create scripts tags for `h1`
- [x] Create handlers for `textarea`
- [x] PR was raised, reviewed by two assigned reviewers and the branch was merged to the `master` branch.

**Comment by LujiAnna** [comment]
`HTML contenteditable Attribute` already makes content editable
